// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMkMz24711kS2wYHLfsWnCdq52AKjVZv4',
    appId: '1:549799402629:web:f32c6776a378d374b01dec',
    messagingSenderId: '549799402629',
    projectId: 'connectify-95bc6',
    authDomain: 'connectify-95bc6.firebaseapp.com',
    storageBucket: 'connectify-95bc6.appspot.com',
    measurementId: 'G-P236GSCVSL',
  );

  // ✅ Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvemvpURHZ60OOOYQrMLsNpfSfbVGiMT0',
    appId: '1:549799402629:android:bae5aa218584218ab01dec',
    messagingSenderId: '549799402629',
    projectId: 'connectify-95bc6',
    storageBucket: 'connectify-95bc6.appspot.com',
  );

  // ✅ iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImq6nR6bJRAVwyE8HRDZP-wnOspjV-Og',
    appId: '1:549799402629:ios:46089f2855978cc5b01dec',
    messagingSenderId: '549799402629',
    projectId: 'connectify-95bc6',
    storageBucket: 'connectify-95bc6.appspot.com',
    iosBundleId: 'com.example.connectify',
  );

  // ✅ macOS configuration (same as iOS)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImq6nR6bJRAVwyE8HRDZP-wnOspjV-Og',
    appId: '1:549799402629:ios:46089f2855978cc5b01dec',
    messagingSenderId: '549799402629',
    projectId: 'connectify-95bc6',
    storageBucket: 'connectify-95bc6.appspot.com',
    iosBundleId: 'com.example.connectify',
  );

  //  Windows configuration (same as Web)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMkMz24711kS2wYHLfsWnCdq52AKjVZv4',
    appId: '1:549799402629:web:c01efb7c369c290eb01dec',
    messagingSenderId: '549799402629',
    projectId: 'connectify-95bc6',
    authDomain: 'connectify-95bc6.firebaseapp.com',
    storageBucket: 'connectify-95bc6.appspot.com',
    measurementId: 'G-S3W2QE85ZP',
  );
}
